spring.application.name=moneymanager
#Mysql config
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://root:oOOJgbxwVddgArktMlZQPMajqvCniZqS@ballast.proxy.rlwy.net:33265/railway}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:root}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:oOOJgbxwVddgArktMlZQPMajqvCniZqS}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
#JPA config
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
#config jwt
minh.jwt.base64-secret=0pewURzaV9XPBUTHIkLSdQ1vMjguCHtpoqKce8Yb+AQ=
#1day
minh.jwt.access-token-validity-in-seconds=864000
minh.jwt.refresh-token-validity-in-seconds=86400000
money.manager.frontend.url=${MONEY_MANAGER_FRONTEND_URL:http://localhost:5173}
app.activation.url=${MONEY_MANAGER_BACKEND_URL:http://localhost:8080}
spring.profiles.active=prod