spring.application.name=moneymanager
#Mysql config
spring.datasource.url=jdbc:mysql://localhost:3306/moneymanager
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
#email config
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=min257358@gmail.com
spring.mail.password=yvvi wqsl xtrm nqgc
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
#JPA config
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
#config jwt
minh.jwt.base64-secret=0pewURzaV9XPBUTHIkLSdQ1vMjguCHtpoqKce8Yb+AQ=
#1day
minh.jwt.access-token-validity-in-seconds=864000
minh.jwt.refresh-token-validity-in-seconds=86400000
money.manager.frontend.url=${MONEY_MANAGER_FRONTEND_URL:http://localhost:5173}
app.activation.url=${MONEY_MANAGER_BACKEND_URL:http://localhost:8080}